# Generated by Django 5.2.16 on 2026-07-22 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(blank=True, choices=[('투', '투수'), ('포', '포수'), ('내', '내야수'), ('외', '외야수')], max_length=10)),
                ('back_number', models.CharField(blank=True, max_length=5)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='roster.team')),
            ],
            options={
                'ordering': ['team__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RosterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ACTIVE_1GUN', '1군 등록'), ('OPTIONED_2GUN', '2군 말소'), ('INJURED', '부상자 명단'), ('MILITARY', '군 입대/전역'), ('SUSPENDED', '출장 정지'), ('RELEASED', '방출/은퇴'), ('OTHER', '기타')], max_length=20)),
                ('event_date', models.DateField()),
                ('reason', models.CharField(blank=True, help_text='부상 부위, 사유 등 (KBO 공식 페이지에는 표기되지 않아 수동 기재)', max_length=200)),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('SCRAPER', '자동 수집'), ('MANUAL', '수동 입력')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='roster.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.team')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('player', 'event_date', 'event_type'), name='unique_event_per_player_per_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_player_name'),
        ),
    ]
