# Generated by Django 5.2.16 on 2026-07-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterevent',
            name='source_name',
            field=models.CharField(blank=True, help_text='사유 출처 (예: 한화 이글스 공식 SNS, 연합뉴스 등)', max_length=100),
        ),
        migrations.AddField(
            model_name='rosterevent',
            name='source_url',
            field=models.URLField(blank=True, help_text='사유 출처 원문 링크'),
        ),
        migrations.AlterField(
            model_name='rosterevent',
            name='reason',
            field=models.CharField(blank=True, help_text='부상 부위, 사유 등 (KBO 공식 페이지에는 표기되지 않아 수동 또는 미디어 수집으로 기재)', max_length=200),
        ),
        migrations.AlterField(
            model_name='rosterevent',
            name='source',
            field=models.CharField(choices=[('SCRAPER', 'KBO 공식 자동 수집'), ('MANUAL', '수동 입력'), ('MEDIA', '미디어/SNS 수집')], default='MANUAL', max_length=10),
        ),
    ]
