# Generated by Django 5.2.16 on 2026-07-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_rosterevent_source_name_rosterevent_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='kbo_player_id',
            field=models.CharField(blank=True, help_text='KBO 공식 사이트 선수 고유 코드 (pcode). 사진 URL 조회 등에 사용', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True, help_text='KBO 공식 사이트 선수 사진 URL (재호스팅하지 않고 링크만 저장)'),
        ),
    ]
