# Generated by Django 5.2.16 on 2026-07-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_player_kbo_player_id_player_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='news_articles_cache',
            field=models.JSONField(blank=True, default=list, help_text='요약 생성에 사용된 기사 목록(제목/설명/링크/날짜) 캐시'),
        ),
        migrations.AddField(
            model_name='player',
            name='news_summary',
            field=models.TextField(blank=True, help_text='네이버 뉴스 기사 기반 AI 요약 캐시'),
        ),
        migrations.AddField(
            model_name='player',
            name='news_summary_updated_at',
            field=models.DateTimeField(blank=True, help_text='AI 요약을 마지막으로 새로 생성한 시각', null=True),
        ),
    ]
