# Generated by Django 5.2.16 on 2026-07-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_player_news_articles_cache_player_news_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('contact', models.CharField(blank=True, help_text='답변 받을 이메일 등 (선택)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False, help_text='개발자 이메일로 발송 성공 여부')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
