# Generated by Django 5.2.16 on 2026-07-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('llm_calls', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
