# Generated by Django 5.2.16 on 2026-07-29 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('instagram_id', models.CharField(max_length=50)),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('date', 'instagram_id'), name='unique_instagram_per_day'), models.UniqueConstraint(fields=('date', 'session_key'), name='unique_session_per_day')],
            },
        ),
        migrations.CreateModel(
            name='PredictionPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(help_text='KBO 경기 고유 ID (G_ID)', max_length=20)),
                ('away_team', models.CharField(max_length=20)),
                ('home_team', models.CharField(max_length=20)),
                ('picked_team', models.CharField(help_text='away_team 또는 home_team 값 중 하나', max_length=20)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='roster.predictionsubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('submission', 'game_id'), name='unique_pick_per_game')],
            },
        ),
    ]
