# Generated by Django 5.2.16 on 2026-08-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_predictionsubmission_predictionpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystat',
            name='unique_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
