# Generated by Django 5.2.16 on 2026-08-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_dailystat_unique_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSummaryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('team_name', models.CharField(blank=True, max_length=20)),
                ('prompt_version', models.CharField(max_length=10)),
                ('articles', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
