# Generated by Django 5.2.16 on 2026-08-30 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_newssummarylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNewsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('articles_cache', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_summaries', to='roster.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'style'), name='unique_player_news_style')],
            },
        ),
    ]
